// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7lXRGmxGp7NoOocsHgaL4PSfuN9PLLQg',
    appId: '1:412525981883:android:675d8deb44cfd88e6cb99e',
    messagingSenderId: '412525981883',
    projectId: 'disaster-app-b2370',
    storageBucket: 'disaster-app-b2370.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZhQYTFTSDBwpZhBbkU6CRov72Oaw4Jz8',
    appId: '1:412525981883:ios:6aa5e3a12eb1bc8d6cb99e',
    messagingSenderId: '412525981883',
    projectId: 'disaster-app-b2370',
    storageBucket: 'disaster-app-b2370.firebasestorage.app',
    iosBundleId: 'com.example.disasterApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA02gUYxEC65E-vFhMFl2Q1lJ_dLD4WDhY',
    appId: '1:412525981883:web:ca8a2782dd9bcec36cb99e',
    messagingSenderId: '412525981883',
    projectId: 'disaster-app-b2370',
    authDomain: 'disaster-app-b2370.firebaseapp.com',
    storageBucket: 'disaster-app-b2370.firebasestorage.app',
    measurementId: 'G-L0786BYSJM',
  );

}