import org.gradle.api.artifacts.dsl.LockMode

// Top-level build file where you can add configuration options common to all sub-projects/modules.
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.android.library) apply false
    alias(libs.plugins.kotlin.compose) apply false
    id("com.google.gms.google-services") version "4.4.4" apply false
}

// Force Mockito version across all subprojects to fix Java 21 compatibility issues
subprojects {
    configurations.all {
        resolutionStrategy.eachDependency {
            if (requested.group == "org.mockito" && requested.name == "mockito-core") {
                useVersion("5.11.0")
            }
        }
    }

    // shared_preferences_android DataStore tests fail on Windows due to file-locking (Robolectric + DataStore rename bug)
    afterEvaluate {
        if (project.name == "shared_preferences_android") {
            tasks.withType(Test::class).configureEach {
                ignoreFailures = true
            }
        }
    }
}

val resolveIdeRuntimeClasspathCopyLocks = tasks.register("resolveIdeRuntimeClasspathCopyLocks") {
    group = "build setup"
    description = "Resolves Android Studio runtime classpath copies when refreshing lock state."
}

// Upstream applies dependency locking to every subproject. The embedded Flutter module
// (":flutter" plus one generated subproject per pub package) is generated by the Flutter
// tool and carries no lockfiles, so locking is scoped to the modules this repo owns.
val lockedProjects = setOf(":app", ":wear")

subprojects {
    if (path in lockedProjects) {
        dependencyLocking {
            lockAllConfigurations()
            lockMode.set(LockMode.STRICT)
        }
    }

    pluginManager.withPlugin("com.android.application") {
        val resolveIdeRuntimeClasspathCopyLock = tasks.register("resolveIdeRuntimeClasspathCopyLock") {
            group = "build setup"
            description = "Resolves this module's Android Studio runtime classpath copies."
            notCompatibleWithConfigurationCache("Resolves copied configurations at execution time")
            doFirst {
                check(gradle.startParameter.isWriteDependencyLocks) {
                    "$path must be run with --write-locks"
                }
            }
            doLast {
                listOf("debugRuntimeClasspath", "releaseRuntimeClasspath").forEach { configurationName ->
                    configurations.getByName(configurationName).copy().resolve()
                }
            }
        }
        resolveIdeRuntimeClasspathCopyLocks.configure {
            dependsOn(resolveIdeRuntimeClasspathCopyLock)
        }
    }
}

tasks.whenTaskAdded {
    if (name.contains("ArtProfile")) {
        enabled = false
    }
}

tasks.register("clientRewriteContractTest") {
    group = "verification"
    description = "Runs the complete compatibility gate for a from-scratch client rewrite."
    dependsOn(":app:testDebugUnitTest")
}
